version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: gestor_biblioteca_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql

  api:
    build:
      context: ./GestorBibliotecaComunitaria/GestorBiblioteca.API
      dockerfile: Dockerfile
    container_name: gestor_biblioteca_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Override the connection string to point at the database service
      - ConnectionStrings__DefaultConnection=Server=db;Database=GestorBiblioteca;User=sa;Password=Your_password123;TrustServerCertificate=True;MultipleActiveResultSets=True
    ports:
      - "5000:80"
    depends_on:
      - db

volumes:
  dbdata: