services:
  gestor.biblioteca.nosql:
    container_name: gestor_biblioteca_database_nosql 
    image: mongo:latest
    environment:
        MONGO_INITDB_ROOT_USERNAME: developer
        MONGO_INITDB_ROOT_PASSWORD: Pass@word86
    ports:
      - "27017:27017"
      
  gestor.biblioteca.api:
    container_name: gestor_biblioteca_api
    build:
        context: .
        dockerfile: Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
    ports:
        - "8080"
        - "8081"
    volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - gestor.biblioteca.nosql
